name: Deploy CDK Stack

on:
    push:
        branches:
            - main
            - feature/AILUMNI-lambda-deployment
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            - name: Set Up Node Project
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install CDK
              run: npm install -g aws-cdk
            - name: Install Deps
              run: npm install
            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-crednetials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-west-2
            - name: Bootstrap CDK
              run: cdk bootstrap
            - name: Synthesize Cloudformation Template
              run: cdk synth
            - name: Deploy CDK Stack
              run: cdk deploy --require-approval never